site_name: Amazon EMR Train-The-Trainer Workshop
repo_name: "vasveena/amazon-emr-ttt-workshop"
repo_url: "https://github.com/vasveena/amazon-emr-ttt-workshop"
docs_dir: "docs"
theme:
  name: material
  features:
    - tabs
nav:
  - Introduction: 'index.md'
  - Setup: 'setup.md'
  - Part 1:
    - 1 - Launching EMR cluster with Instance Fleets: 'day1/fleet/exercise.md'
    - 2 - Apache Spark on Amazon EMR: 'day1/spark/exercise.md'
    - 3 - Orchestrate EMR Steps using AWS Step Functions: 'day1/step/exercise.md'
  - Part 2:
    - 1 - Amazon EMR Studio: 'day1/studio/exercise.md'
    - 2 - Orchestration Notebook Pipelines using Amazon MWAA: 'day1/mwaa/exercise.md'
    - 3 - Sagemaker Studio Integration: 'day2/smstudio/exercise.md'
  - Part 3:
    - Build Incremental Data Lakes:
      - 1 - Apache Hudi on Amazon EMR: 'day2/hudi/exercise.md'
      - 2 - Apache Iceberg on Amazon EMR: 'day2/icebrg/exercise.md'
  - Part 4:
    - Deployment Options:
      - Introduction: 'day3/index.md'
      - 1 - Amazon EMR on EKS: 'day3/emroneks/exercise.md'
      - 2 - Amazon EMR Serverless: 'day3/serverless/exercise.md'
  # - Part 5:
  #  - LakeFormation Integration: 'day3/lf/exercise.md'
  # - Part 6:
  #  - 1 - Hive and Presto on Amazon EMR: 'day3/hive/exercise.md'
  #  - 2 - HBase on S3: 'day3/hbase/exercise.md'
markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - codehilite
    - attr_list
    - md_in_html
